### ISSUE TITLE
Genebass hail format

### ISSUE THREAD

**Issue by dheeraj-bobbili1988** [Nealelab/ukb_exomes#52]
Hi,

First of all thank you for making this repo public. I am trying to convert all the hail matrix files to flat txt files for all the phenotypes. I tried using the hail library. The file that I am trying to convert is ```gs://ukbb-pharma-exome-analysis-300k/300k/results/variant_results.mt``` and the function that I used was ```mt.entries()```

However, with that function, there is a problem with the memory and it errors out. Could you please suggest a way to generate a phenotype file?

Sorry, I know you are not the hail developer but since you worked on this dataset. I thought you might have any pointers.

Thank you,
Dheeraj.

**Comment by konradjk** [comment]
Do you want one flat file per phenotype? You might have more luck looking at the hail tables in: `gs://ukbb-exome-public/300k/results/per_phenotype_hail_tables/` and exporting each of those. For just a few phenotypes, this is probably the way to go, but if you really want all the data, you might find it easier to do your analyses within the Hail framework.

**Comment by yu-zhang-oYo** [comment]
> per_phenotype_hail_tables

Hi, 

is there any way to use wget to download those per phenotype table, so that I don't need to figure out how to use hail to download them? Besides, there is suppposed to be [Phenotype metadata in tsv format (bgzipped)](https://storage.googleapis.com/ukbb-exome-public/500k/results/pheno_results.txt.bgz) on this page https://app.genebass.org/downloads, but it does not work, could you please help me figure it out? Any help would be appreciated.

Thanks
Yu
